name: amt-competition-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
    - librosa==0.8.0
    - tensorflow==2.7.0
    - numpy==1.21.4
    - scipy==1.7.3
    - ffmpeg
    - pydub
